// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:21fd158e-4edf-405b-bf73-13aa548c6378",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_azVcvbifI",
    "aws_user_pools_web_client_id": "775pd3mu5o6iilj0lens6k70jn",
    "aws_dynamodb_all_tables_region": "eu-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamo142a8756",
            "region": "eu-central-1"
        }
    ]
};


export default awsmobile;
